package com.lebhas.ai.application.dto;

import com.lebhas.ai.domain.CredentialStatus;
import com.lebhas.ai.domain.ProviderConnectionTestStatus;
import com.lebhas.ai.domain.ProviderEnvironment;
import com.lebhas.ai.domain.ProviderStatus;
import com.lebhas.ai.domain.ProviderType;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record MasterProviderView(
        UUID id,
        String providerKey,
        String providerCode,
        String displayName,
        String category,
        ProviderType providerType,
        ProviderStatus status,
        String description,
        List<String> supportedCapabilities,
        String baseUrl,
        String defaultModel,
        String modelsEndpoint,
        String modelsEndpointAuth,
        String apiKeyQueryParam,
        String sendSmsEndpoint,
        String balanceEndpoint,
        String requestMethod,
        String senderId,
        Integer otpLength,
        Integer otpExpiryMinutes,
        Integer resendCooldownSeconds,
        Integer maxAttempts,
        Boolean balanceMonitoringEnabled,
        Boolean healthCheckEnabled,
        List<ProviderEnvironment> supportedEnvironments,
        boolean supportsSandbox,
        boolean supportsLive,
        ProviderEnvironment defaultEnvironment,
        CredentialStatus credentialStatus,
        boolean credentialConfigured,
        ProviderEnvironment activeEnvironment,
        BigDecimal availableCreditBalance,
        boolean webhookConfigured,
        String webhookUrl,
        ProviderConnectionTestStatus lastTestStatus,
        Instant lastTestedAt,
        String lastTestMessage,
        boolean active,
        boolean systemDefault,
        String maskedApiKey,
        Integer priority,
        Integer rateLimitPerMinute,
        BigDecimal costMultiplier,
        String maskedOpenAiAdminApiKey,
        BigDecimal providerTopUpAmountUsd,
        LocalDate providerTopUpDate,
        BigDecimal providerManualBalanceUsd,
        Instant lastCostSyncAt,
        BigDecimal totalCostSpentUsd,
        BigDecimal estimatedRemainingBalanceUsd,
        BigDecimal estimatedInternalCredits,
        Boolean costSyncEnabled,
        String balanceHealth,
        String metadataJson,
        boolean secretsHidden,
        Instant credentialUpdatedAt,
        Instant createdAt,
        Instant updatedAt
) {
}
