package com.lebhas.ai.credit.domain;

public enum ProviderCreditTransactionType {
    PROVIDER_BALANCE_SET,
    PROVIDER_BALANCE_ADJUSTED,
    FREE_SIGNUP_CREDIT_GRANTED,
    CREDIT_PURCHASED,
    CREDIT_RESERVED,
    CREDIT_FINALIZED,
    CREDIT_REFUNDED,
    PROVIDER_CREDIT_RESERVED,
    PROVIDER_CREDIT_USED,
    PROVIDER_CREDIT_RELEASED,
    MANUAL_ADJUSTMENT
}
