import { NavigationItem } from '@app/shared/layouts/navigation.models';

export const DASHBOARD_NAVIGATION: readonly NavigationItem[] = [
  {
    label: 'Dashboard',
    icon: 'layout-dashboard',
    route: '/dashboard',
    group: 'Workspace',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'exact',
  },
  {
    label: 'Brands',
    icon: 'badge-check',
    route: '/brands',
    group: 'Workspace',
    roles: ['ADMIN'],
    permissionKey: 'canViewBrands',
    activeMatch: 'prefix',
  },
  {
    label: 'Products / Services',
    icon: 'package-open',
    route: '/product-services',
    group: 'Workspace',
    roles: ['ADMIN'],
    permissionKey: 'canViewProducts',
    activeMatch: 'prefix',
  },
  {
    label: 'Projects / Campaigns',
    icon: 'folder-kanban',
    route: '/projects',
    group: 'Workspace',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewProjects',
    activeMatch: 'prefix',
  },
  {
    label: 'Assets Library',
    icon: 'image',
    route: '/assets',
    group: 'Workspace',
    roles: ['ADMIN'],
    activePaths: ['/projects/:projectId/assets'],
    activeMatch: 'prefix',
  },
  {
    label: 'Creative Generator',
    icon: 'wand-sparkles',
    route: '/creative-generator',
    group: 'Create',
    roles: ['ADMIN'],
    activeMatch: 'prefix',
  },
  {
    label: 'Post Generator',
    icon: 'megaphone',
    route: '/post-generator',
    group: 'Create',
    roles: ['ADMIN'],
    activeMatch: 'prefix',
  },
  {
    label: 'Captions',
    icon: 'pencil-line',
    route: '/captions',
    group: 'Create',
    roles: ['ADMIN'],
    activeMatch: 'prefix',
  },
  {
    label: 'Ad Copy',
    icon: 'receipt-text',
    route: '/ad-copy',
    group: 'Create',
    roles: ['ADMIN'],
    activeMatch: 'prefix',
  },
  {
    label: 'Hashtags',
    icon: 'tag',
    route: '/hashtags',
    group: 'Create',
    roles: ['ADMIN'],
    activeMatch: 'prefix',
  },
  {
    label: 'Generated Versions',
    icon: 'grid-2x2',
    route: '/generated-versions',
    group: 'Review',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'prefix',
  },
  {
    label: 'Approvals',
    icon: 'shield-check',
    route: '/approvals',
    group: 'Review',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'prefix',
  },
  {
    label: 'Payments',
    icon: 'credit-card',
    route: '/payments',
    group: 'Billing',
    roles: ['ADMIN'],
    permissionKey: 'canViewPayments',
    activeMatch: 'exact',
  },
  {
    label: 'Credit Usage',
    icon: 'wallet-cards',
    route: '/credit-usage',
    group: 'Billing',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewUsageBilling',
    activePaths: ['/usage-billing'],
    activeMatch: 'prefix',
  },
  {
    label: 'Profile',
    icon: 'user-round',
    route: '/profile',
    group: 'Account',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'exact',
  },
  {
    label: 'Settings',
    icon: 'settings',
    route: '/profile/settings',
    group: 'Account',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'prefix',
  },
  {
    label: 'System Dashboard',
    icon: 'layout-dashboard',
    route: '/master/dashboard',
    group: 'System',
    roles: ['MASTER'],
    activeMatch: 'exact',
  },
  {
    label: 'Workspaces',
    icon: 'building-2',
    route: '/master/usage/workspaces',
    group: 'System',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'Users / Admins',
    icon: 'users',
    route: '/audit-logs',
    group: 'System',
    roles: ['MASTER'],
    permissionKey: 'canViewAuditLogs',
    activeMatch: 'prefix',
  },
  {
    label: 'Creative Tools',
    icon: 'wand-sparkles',
    route: '/master/creative-tools',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewAiMonitoring',
    activeMatch: 'exact',
  },
  {
    label: 'Creative Layers',
    icon: 'layers-3',
    route: '/master/creative-layers',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewLayerAnalytics',
    activeMatch: 'exact',
  },
  {
    label: 'Provider Routing',
    icon: 'route',
    route: '/master/provider-routing',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewAiMonitoring',
    activeMatch: 'exact',
  },
  {
    label: 'Provider Settings',
    icon: 'settings',
    route: '/master/provider-settings',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canManagePaymentProviders',
    activeMatch: 'exact',
  },
  {
    label: 'Provider Health',
    icon: 'heart-pulse',
    route: '/master/provider-health',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewProviderMetrics',
    activePaths: ['/ai-monitoring/providers', '/ai-monitoring/providers/metrics', '/provider-health'],
    activeMatch: 'exact',
  },
  {
    label: 'Layer Analytics',
    icon: 'bar-chart-3',
    route: '/master/layer-analytics',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewLayerAnalytics',
    activeMatch: 'exact',
  },
  {
    label: 'AI Cost Usage',
    icon: 'wallet-cards',
    route: '/master/ai-cost-usage',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewAiMonitoring',
    activeMatch: 'exact',
  },
  {
    label: 'Pricing Packages',
    icon: 'package-check',
    route: '/master/pricing-packages',
    group: 'Monetization',
    roles: ['MASTER'],
    activeMatch: 'exact',
  },
  {
    label: 'Credit Packages',
    icon: 'package-plus',
    route: '/master/credit-packages',
    group: 'Monetization',
    roles: ['MASTER'],
    permissionKey: 'canManageCreditPackages',
    activeMatch: 'exact',
  },
  {
    label: 'Payment Providers',
    icon: 'credit-card',
    route: '/master/payment-providers',
    group: 'Monetization',
    roles: ['MASTER'],
    permissionKey: 'canManagePaymentProviders',
    activeMatch: 'exact',
  },
  {
    label: 'Payment Transactions',
    icon: 'receipt-text',
    route: '/master/payment-transactions',
    group: 'Monetization',
    roles: ['MASTER'],
    permissionKey: 'canViewPayments',
    activeMatch: 'exact',
  },
  {
    label: 'Usage Overview',
    icon: 'chart-no-axes-combined',
    route: '/master/usage-overview',
    group: 'Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'exact',
  },
  {
    label: 'Workspace Usage',
    icon: 'building-2',
    route: '/master/workspace-usage',
    group: 'Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'exact',
  },
  {
    label: 'AI Failures',
    icon: 'triangle-alert',
    route: '/master/ai-failures',
    group: 'Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewAiFailures',
    activeMatch: 'exact',
  },
  {
    label: 'Audit Logs',
    icon: 'shield-check',
    route: '/audit-logs',
    group: 'Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewAuditLogs',
    activeMatch: 'exact',
  },
  {
    label: 'System Health',
    icon: 'gauge',
    route: '/master/monitoring/system-health',
    group: 'Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewSystemHealth',
    activePaths: ['/monitoring/system-health'],
    activeMatch: 'prefix',
  },
];
