import { NavigationItem } from '@app/shared/layouts/navigation.models';

export const DASHBOARD_NAVIGATION: readonly NavigationItem[] = [
  {
    label: 'System Dashboard',
    icon: 'layout-dashboard',
    route: '/dashboard',
    group: 'Overview',
    roles: ['MASTER'],
    activeMatch: 'exact',
  },
  {
    label: 'Dashboard',
    icon: 'layout-dashboard',
    route: '/dashboard',
    group: 'Workspace',
    roles: ['ADMIN', 'CREW'],
    activeMatch: 'exact',
  },
  {
    label: 'Brands',
    icon: 'badge-check',
    route: '/brands',
    group: 'Workspace',
    roles: ['ADMIN'],
    permissionKey: 'canViewBrands',
    activeMatch: 'prefix',
  },
  {
    label: 'Products/Services',
    icon: 'package-open',
    route: '/product-services',
    group: 'Workspace',
    roles: ['ADMIN'],
    permissionKey: 'canViewProducts',
    activeMatch: 'prefix',
  },
  {
    label: 'Projects/Campaigns',
    icon: 'folder-kanban',
    route: '/projects',
    group: 'Workspace',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewProjects',
    activeMatch: 'prefix',
  },
  {
    label: 'Approvals',
    icon: 'shield-check',
    route: '/approvals',
    group: 'Overview',
    roles: ['MASTER', 'ADMIN', 'CREW'],
    activeMatch: 'prefix',
  },
  {
    label: 'AI Dashboard',
    icon: 'activity',
    route: '/ai-monitoring',
    group: 'AI Operations',
    roles: ['MASTER', 'CREW'],
    permissionKey: 'canViewAiMonitoring',
    activeMatch: 'exact',
  },
  {
    label: 'Provider Health',
    icon: 'heart-pulse',
    route: '/ai-monitoring/providers',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewProviderMetrics',
    activePaths: ['/ai-monitoring/providers', '/ai-monitoring/providers/metrics', '/provider-health'],
    activeMatch: 'prefix',
  },
  {
    label: 'Layer Analytics',
    icon: 'layers-3',
    route: '/ai-monitoring/layers',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewLayerAnalytics',
    activeMatch: 'prefix',
  },
  {
    label: 'Workspace AI Usage',
    icon: 'building-2',
    route: '/ai-monitoring/workspaces',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewWorkspaceAiUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'AI Usage',
    icon: 'activity',
    route: '/ai-monitoring/workspaces',
    roles: ['ADMIN'],
    permissionKey: 'canViewWorkspaceAiUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'Quality Scores',
    icon: 'star',
    route: '/ai-monitoring/quality',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewQualityScores',
    activeMatch: 'prefix',
  },
  {
    label: 'AI Failures',
    icon: 'triangle-alert',
    route: '/ai-monitoring/failures',
    group: 'AI Operations',
    roles: ['MASTER'],
    permissionKey: 'canViewAiFailures',
    activeMatch: 'prefix',
  },
  {
    label: 'Usage Overview',
    icon: 'receipt-text',
    route: '/usage-billing',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewUsageBilling',
    activeMatch: 'exact',
  },
  {
    label: 'Credit Ledger',
    icon: 'wallet-cards',
    route: '/usage-billing/credits',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewCreditLedger',
    activeMatch: 'prefix',
  },
  {
    label: 'Usage Logs',
    icon: 'list-checks',
    route: '/usage-billing/logs',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewUsageBilling',
    activeMatch: 'prefix',
  },
  {
    label: 'Downloads',
    icon: 'download',
    route: '/usage-billing/downloads',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewDownloadUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'Shares',
    icon: 'share-2',
    route: '/usage-billing/shares',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewShareUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'Payments',
    icon: 'credit-card',
    route: '/payments',
    group: 'Workspace',
    roles: ['ADMIN'],
    permissionKey: 'canViewPayments',
    activeMatch: 'exact',
  },
  {
    label: 'Subscription',
    icon: 'badge-dollar-sign',
    route: '/payments/subscription',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canPurchaseSubscription',
    activeMatch: 'prefix',
  },
  {
    label: 'Buy Credits',
    icon: 'wallet-cards',
    route: '/payments/credits',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canPurchaseCredits',
    activeMatch: 'prefix',
  },
  {
    label: 'Payment History',
    icon: 'receipt-text',
    route: '/payments/transactions',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewPayments',
    activeMatch: 'prefix',
  },
  {
    label: 'Invoices',
    icon: 'file-text',
    route: '/payments/invoices',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewInvoices',
    activeMatch: 'prefix',
  },
  {
    label: 'Notifications',
    icon: 'bell',
    route: '/notifications',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewNotifications',
    activeMatch: 'exact',
  },
  {
    label: 'Notification Settings',
    icon: 'settings',
    route: '/notifications/preferences',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canManageNotificationPreferences',
    activeMatch: 'prefix',
  },
  {
    label: 'Activity Feed',
    icon: 'activity',
    route: '/activity-feed',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewActivityFeed',
    activeMatch: 'exact',
  },
  {
    label: 'Workspace Timeline',
    icon: 'list-checks',
    route: '/workspace-timeline',
    roles: ['ADMIN', 'CREW'],
    permissionKey: 'canViewActivityFeed',
    activeMatch: 'exact',
  },
  {
    label: 'Audit Logs',
    icon: 'shield-check',
    route: '/audit-logs',
    group: 'System Monitoring',
    roles: ['MASTER', 'ADMIN', 'CREW'],
    permissionKey: 'canViewAuditLogs',
    activeMatch: 'exact',
  },
  {
    label: 'Monitoring Overview',
    icon: 'heart-pulse',
    route: '/master/monitoring',
    group: 'System Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterMonitoring',
    activePaths: ['/monitoring'],
    activeMatch: 'exact',
  },
  {
    label: 'System Health',
    icon: 'gauge',
    route: '/master/monitoring/system-health',
    group: 'System Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewSystemHealth',
    activePaths: ['/monitoring/system-health'],
    activeMatch: 'prefix',
  },
  {
    label: 'Alerts',
    icon: 'triangle-alert',
    route: '/master/monitoring/alerts',
    group: 'System Monitoring',
    roles: ['MASTER'],
    permissionKey: 'canViewMonitoringAlerts',
    activePaths: ['/monitoring/alerts'],
    activeMatch: 'prefix',
  },
  {
    label: 'Usage Overview',
    icon: 'chart-no-axes-combined',
    route: '/master/usage',
    group: 'Usage & Billing',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'exact',
  },
  {
    label: 'Workspace Usage',
    icon: 'building-2',
    route: '/master/usage/workspaces',
    group: 'Usage & Billing',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'AI Cost Usage',
    icon: 'wallet-cards',
    route: '/master/usage/ai-costs',
    group: 'Usage & Billing',
    roles: ['MASTER'],
    permissionKey: 'canViewMasterUsage',
    activeMatch: 'prefix',
  },
  {
    label: 'Plan Utilization',
    icon: 'package-check',
    route: '/master/usage/plan-utilization',
    group: 'Usage & Billing',
    roles: ['MASTER'],
    permissionKey: 'canViewPlanUtilization',
    activeMatch: 'prefix',
  },
  {
    label: 'Payment Providers',
    icon: 'credit-card',
    route: '/master/payments/providers',
    group: 'Payments',
    roles: ['MASTER'],
    permissionKey: 'canManagePaymentProviders',
    activeMatch: 'prefix',
  },
  {
    label: 'Provider Settings',
    icon: 'settings',
    route: '/master/payments/provider-configurations',
    group: 'Payments',
    roles: ['MASTER'],
    permissionKey: 'canManagePaymentProviders',
    activeMatch: 'prefix',
  },
  {
    label: 'Credit Packages',
    icon: 'package-plus',
    route: '/master/payments/credit-packages',
    group: 'Payments',
    roles: ['MASTER'],
    permissionKey: 'canManageCreditPackages',
    activeMatch: 'prefix',
  },
  {
    label: 'Payment Transactions',
    icon: 'receipt-text',
    route: '/master/payments/transactions',
    group: 'Payments',
    roles: ['MASTER'],
    permissionKey: 'canViewPayments',
    activeMatch: 'prefix',
  },
];
