package com.lebhas.creativesaas.auditlog.domain;

public enum AuditActionType {
    CREATE,
    UPDATE,
    DELETE,
    READ,
    LOGIN,
    LOGOUT,
    APPROVE,
    REJECT,
    PURCHASE,
    PROCESS,
    ACCESS,
    SYSTEM,
    PROFILE_UPDATED,
    SETTINGS_UPDATED,
    PROFILE_IMAGE_UPLOAD_REQUESTED,
    PROFILE_IMAGE_UPDATED,
    PROFILE_IMAGE_REMOVED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    SESSION_REVOKED,
    UNAUTHORIZED_PROFILE_ACCESS_ATTEMPT
}
