package com.lebhas.creativesaas.operations.domain;

public enum SystemFeatureToggleKey {
    AI_GENERATION_ENABLED,
    ASSET_UPLOAD_ENABLED,
    PROMPT_ENHANCEMENT_ENABLED,
    TEXT_TOOLS_ENABLED,
    IMAGE_CREATIVE_GENERATION_ENABLED,
    APPROVAL_WORKFLOW_ENABLED,
    PUBLIC_SHARING_ENABLED,
    DOWNLOADS_ENABLED,
    PAYMENTS_ENABLED,
    REGISTRATION_ENABLED,
    WORKSPACE_CREATION_ENABLED,
    MAINTENANCE_MODE,
    BETA_ONLY_MODE
}
