package com.lebhas.creativesaas.pricing.application.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Set;
import java.util.UUID;

public record PlanFeaturePolicyView(
        UUID id,
        UUID pricingPlanId,
        Integer maxGeneratedVersionsPerRequest,
        Integer maxBrands,
        Integer maxProductServices,
        Integer maxProjects,
        Integer maxAssets,
        Integer maxCreativeRequests,
        Integer maxTeamMembers,
        Integer maxGeneratedVersionsPerCreativeRequest,
        BigDecimal maxStorageGb,
        Long maxStorageBytes,
        BigDecimal monthlyCreditLimit,
        boolean promptEnhancementEnabled,
        boolean creativeGenerationEnabled,
        boolean allowApprovalWorkflow,
        boolean downloadEnabled,
        boolean shareEnabled,
        boolean allowPublicShareLinks,
        boolean assetUploadEnabled,
        boolean premiumQualityEnabled,
        boolean allowVideoGeneration,
        boolean voiceoverGenerationEnabled,
        boolean allowAdvancedPromptIntelligence,
        boolean allowTeamCollaboration,
        boolean allowExportWithoutWatermark,
        Set<String> enabledCreativeToolCodes,
        Instant createdAt,
        Instant updatedAt
) {
    public PlanFeaturePolicyView(
            UUID id,
            UUID pricingPlanId,
            Integer maxGeneratedVersionsPerRequest,
            Integer maxBrands,
            Integer maxProductServices,
            Integer maxProjects,
            Integer maxAssets,
            Integer maxCreativeRequests,
            Integer maxTeamMembers,
            Integer maxGeneratedVersionsPerCreativeRequest,
            BigDecimal maxStorageGb,
            Long maxStorageBytes,
            BigDecimal monthlyCreditLimit,
            boolean promptEnhancementEnabled,
            boolean creativeGenerationEnabled,
            boolean allowApprovalWorkflow,
            boolean downloadEnabled,
            boolean shareEnabled,
            boolean allowPublicShareLinks,
            boolean assetUploadEnabled,
            boolean premiumQualityEnabled,
            boolean allowVideoGeneration,
            boolean voiceoverGenerationEnabled,
            boolean allowAdvancedPromptIntelligence,
            boolean allowTeamCollaboration,
            boolean allowExportWithoutWatermark,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(
                id,
                pricingPlanId,
                maxGeneratedVersionsPerRequest,
                maxBrands,
                maxProductServices,
                maxProjects,
                maxAssets,
                maxCreativeRequests,
                maxTeamMembers,
                maxGeneratedVersionsPerCreativeRequest,
                maxStorageGb,
                maxStorageBytes,
                monthlyCreditLimit,
                promptEnhancementEnabled,
                creativeGenerationEnabled,
                allowApprovalWorkflow,
                downloadEnabled,
                shareEnabled,
                allowPublicShareLinks,
                assetUploadEnabled,
                premiumQualityEnabled,
                allowVideoGeneration,
                voiceoverGenerationEnabled,
                allowAdvancedPromptIntelligence,
                allowTeamCollaboration,
                allowExportWithoutWatermark,
                Set.of(),
                createdAt,
                updatedAt);
    }

    public PlanFeaturePolicyView(
            UUID id,
            UUID pricingPlanId,
            Integer maxGeneratedVersionsPerRequest,
            Integer maxBrands,
            Integer maxProductServices,
            Integer maxProjects,
            Integer maxTeamMembers,
            BigDecimal maxStorageGb,
            BigDecimal monthlyCreditLimit,
            boolean allowApprovalWorkflow,
            boolean allowPublicShareLinks,
            boolean allowVideoGeneration,
            boolean allowAdvancedPromptIntelligence,
            boolean allowTeamCollaboration,
            boolean allowExportWithoutWatermark,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(
                id,
                pricingPlanId,
                maxGeneratedVersionsPerRequest,
                maxBrands,
                maxProductServices,
                maxProjects,
                null,
                null,
                maxTeamMembers,
                maxGeneratedVersionsPerRequest,
                maxStorageGb,
                null,
                monthlyCreditLimit,
                allowAdvancedPromptIntelligence,
                true,
                allowApprovalWorkflow,
                true,
                allowPublicShareLinks,
                allowPublicShareLinks,
                true,
                false,
                allowVideoGeneration,
                false,
                allowAdvancedPromptIntelligence,
                allowTeamCollaboration,
                allowExportWithoutWatermark,
                Set.of(),
                createdAt,
                updatedAt);
    }
}
