package com.lebhas.ai.domain;

public enum CreativeLayerType {
    INPUT_UNDERSTANDING,
    PRODUCT_ANALYSIS,
    SEGMENTATION,
    BRAND_RULES,
    PROMPT_ENGINEERING,
    MODEL_GENERATION,
    PRODUCT_PRESERVATION,
    BACKGROUND_GENERATION,
    TEXT_RENDERING,
    LOGO_COMPOSITION,
    QUALITY_CONTROL,
    EXPORT,
    BILLING_FINALIZATION
}
