package com.lebhas.ai.domain;

public enum CreativeLayerType {
    INPUT_UNDERSTANDING,
    PROMPT_UNDERSTANDING,
    BRAND_CONTEXT,
    PRODUCT_CONTEXT,
    CREATIVE_GENERATION,
    QUALITY_REVIEW,
    EXPORT_PREPARATION,
    BRAND_CONTEXT_VALIDATION,
    ASSET_ANALYSIS,
    CREATIVE_COMPOSITION,
    QUALITY_SCORING,
    OUTPUT_PREPARATION,
    PRODUCT_ANALYSIS,
    SEGMENTATION,
    BRAND_RULES,
    PROMPT_ENGINEERING,
    MODEL_GENERATION,
    PRODUCT_PRESERVATION,
    BACKGROUND_GENERATION,
    TEXT_RENDERING,
    LOGO_COMPOSITION,
    QUALITY_CONTROL,
    EXPORT,
    BILLING_FINALIZATION
}
